#
# Copyright Greg Haskins All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
FROM _NS_/fabric-basejvm:_TAG_
COPY scripts /tmp/scripts
RUN cd /tmp/scripts && \
    common/packages.sh && \
    common/setup.sh && \
    docker/fixup.sh && \
    common/cleanup.sh && \
    rm -rf /tmp/scripts

# update system packages
RUN apt-get update -qq \
    && apt-get -y upgrade \
    && apt-get clean autoclean \
    && apt-get autoremove -y \
    && rm -rf /var/lib/cache /var/lib/log

ENV GOPATH=/opt/gopath
ENV GOROOT=/opt/go
ENV GOCACHE=off
ENV PATH=$PATH:$GOROOT/bin:$GOPATH/bin
